name:                pure-prolog
version:             0.1.2
synopsis:            Pure Prolog interpreter
author:              Ken Friis Larsen
maintainer:          ken@friislarsen.net
copyright:           Ken Friis Larsen, 2012-2018
extra-source-files:  README.md

dependencies:
  - base < 5

library:
  source-dirs: src
  exposed-modules:
    - Ast
    - Analysis
    - Parser
    - Interp
  dependencies:
    - pretty
    - parsec
    - containers

# A simple command-line driver that uses the library
executable:
  main: Main.hs
  dependencies:
    - pure-prolog
    - cmdargs

# The test-suite
# tests:
#   prolog-test-suite:
#     main: Test.hs
#     source-dirs: tests
#     dependencies:
#     - pure-prolog
#     - tasty
